// <auto-generated />
namespace WebAS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddressIdToLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddressIdToLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201502261007296_AddressIdToLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
