//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAS.Resources.ViewResource", typeof(ViewResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ActionLinkAccountForgotPassword {
            get {
                return ResourceManager.GetString("ActionLinkAccountForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string ActionLinkAccountLoginRegister {
            get {
                return ResourceManager.GetString("ActionLinkAccountLoginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string ActionLinkBackToList {
            get {
                return ResourceManager.GetString("ActionLinkBackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Map.
        /// </summary>
        public static string ActionLinkBackToMap {
            get {
                return ResourceManager.GetString("ActionLinkBackToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ActionLinkChangePassword {
            get {
                return ResourceManager.GetString("ActionLinkChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string ActionLinkCreateNew {
            get {
                return ResourceManager.GetString("ActionLinkCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string ActionLinkLocations {
            get {
                return ResourceManager.GetString("ActionLinkLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string ActionLinkMap {
            get {
                return ResourceManager.GetString("ActionLinkMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ActionLinkRegisterAccountRegisterLink {
            get {
                return ResourceManager.GetString("ActionLinkRegisterAccountRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ActionLinkSetPassword {
            get {
                return ResourceManager.GetString("ActionLinkSetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string ButtonLearnMore {
            get {
                return ResourceManager.GetString("ButtonLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string ButtonMore {
            get {
                return ResourceManager.GetString("ButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ButtonSubmitChangePassword {
            get {
                return ResourceManager.GetString("ButtonSubmitChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string ButtonSubmitCreate {
            get {
                return ResourceManager.GetString("ButtonSubmitCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonSubmitDelete {
            get {
                return ResourceManager.GetString("ButtonSubmitDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string ButtonSubmitEmailLink {
            get {
                return ResourceManager.GetString("ButtonSubmitEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refesh map.
        /// </summary>
        public static string ButtonSubmitLocationMapRefresh {
            get {
                return ResourceManager.GetString("ButtonSubmitLocationMapRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string ButtonSubmitLogin {
            get {
                return ResourceManager.GetString("ButtonSubmitLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string ButtonSubmitRegister {
            get {
                return ResourceManager.GetString("ButtonSubmitRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSubmitSave {
            get {
                return ResourceManager.GetString("ButtonSubmitSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string H1Error {
            get {
                return ResourceManager.GetString("H1Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out..
        /// </summary>
        public static string H1Logout {
            get {
                return ResourceManager.GetString("H1Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string H2Error {
            get {
                return ResourceManager.GetString("H2Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string H2IndexComponent {
            get {
                return ResourceManager.GetString("H2IndexComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string H2IndexDescription {
            get {
                return ResourceManager.GetString("H2IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todo.
        /// </summary>
        public static string H2IndexTodo {
            get {
                return ResourceManager.GetString("H2IndexTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string H2Logout {
            get {
                return ResourceManager.GetString("H2Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string H3LocationDelete {
            get {
                return ResourceManager.GetString("H3LocationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string H4AccountForgotPassword {
            get {
                return ResourceManager.GetString("H4AccountForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification code.
        /// </summary>
        public static string H4AccountSendCode {
            get {
                return ResourceManager.GetString("H4AccountSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider:.
        /// </summary>
        public static string H4AccountSendCodeText {
            get {
                return ResourceManager.GetString("H4AccountSendCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string H4LocationCreate {
            get {
                return ResourceManager.GetString("H4LocationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string H4LocationDelete {
            get {
                return ResourceManager.GetString("H4LocationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string H4LocationDetails {
            get {
                return ResourceManager.GetString("H4LocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string H4LocationEdit {
            get {
                return ResourceManager.GetString("H4LocationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string H4ManageChangePassword {
            get {
                return ResourceManager.GetString("H4ManageChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string H4ManageIndex {
            get {
                return ResourceManager.GetString("H4ManageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Application for storing location data added with description.
        /// </summary>
        public static string LeadHome {
            get {
                return ResourceManager.GetString("LeadHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# ASP.NET.
        /// </summary>
        public static string TextIndexComponentUl1Li1 {
            get {
                return ResourceManager.GetString("TextIndexComponentUl1Li1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVC 5.
        /// </summary>
        public static string TextIndexComponentUl1Li2 {
            get {
                return ResourceManager.GetString("TextIndexComponentUl1Li2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EF 6.
        /// </summary>
        public static string TextIndexComponentUl1Li3 {
            get {
                return ResourceManager.GetString("TextIndexComponentUl1Li3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JQuery.
        /// </summary>
        public static string TextIndexComponentUl1Li4 {
            get {
                return ResourceManager.GetString("TextIndexComponentUl1Li4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Bootstrap.
        /// </summary>
        public static string TextIndexComponentUl1Li5 {
            get {
                return ResourceManager.GetString("TextIndexComponentUl1Li5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bing Map Control V7.0.
        /// </summary>
        public static string TextIndexComponentUl1Li6 {
            get {
                return ResourceManager.GetString("TextIndexComponentUl1Li6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource-files for Globalization.
        /// </summary>
        public static string TextIndexComponentUl1Li7 {
            get {
                return ResourceManager.GetString("TextIndexComponentUl1Li7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration.
        /// </summary>
        public static string TextIndexComponentUl1Li8 {
            get {
                return ResourceManager.GetString("TextIndexComponentUl1Li8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application you can save, change and delete a location data added with description..
        /// </summary>
        public static string TextIndexDescriptionP1 {
            get {
                return ResourceManager.GetString("TextIndexDescriptionP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application use an UI autodetection for the language settings. The default language is English..
        /// </summary>
        public static string TextIndexDescriptionP2 {
            get {
                return ResourceManager.GetString("TextIndexDescriptionP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has been createad two default user roles: Admin (can create new users) and User..
        /// </summary>
        public static string TextIndexDescriptionP3 {
            get {
                return ResourceManager.GetString("TextIndexDescriptionP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User and and role definitions found from file Migrations/Configuration.cs..
        /// </summary>
        public static string TextIndexDescriptionP4 {
            get {
                return ResourceManager.GetString("TextIndexDescriptionP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a correct ReturnUrl for actions Create, Edit and Delete..
        /// </summary>
        public static string TextIndexTodoP1 {
            get {
                return ResourceManager.GetString("TextIndexTodoP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string TitleAccountForgotPassword {
            get {
                return ResourceManager.GetString("TitleAccountForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string TitleAccountLogin {
            get {
                return ResourceManager.GetString("TitleAccountLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string TitleAccountRegister {
            get {
                return ResourceManager.GetString("TitleAccountRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string TitleAccountSendCode {
            get {
                return ResourceManager.GetString("TitleAccountSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string TitleAccountVerifyCode {
            get {
                return ResourceManager.GetString("TitleAccountVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TitleHomeAbout {
            get {
                return ResourceManager.GetString("TitleHomeAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string TitleHomeContact {
            get {
                return ResourceManager.GetString("TitleHomeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string TitleHomeIndex {
            get {
                return ResourceManager.GetString("TitleHomeIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string TitleLocationCreate {
            get {
                return ResourceManager.GetString("TitleLocationCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TitleLocationDelete {
            get {
                return ResourceManager.GetString("TitleLocationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TitleLocationDetails {
            get {
                return ResourceManager.GetString("TitleLocationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TitleLocationEdit {
            get {
                return ResourceManager.GetString("TitleLocationEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string TitleLocationIndex {
            get {
                return ResourceManager.GetString("TitleLocationIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string TitleLocationMap {
            get {
                return ResourceManager.GetString("TitleLocationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Out.
        /// </summary>
        public static string TitleLogout {
            get {
                return ResourceManager.GetString("TitleLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string TitleManageAddPhoneNumber {
            get {
                return ResourceManager.GetString("TitleManageAddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string TitleManageChangePassword {
            get {
                return ResourceManager.GetString("TitleManageChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string TitleManageIndex {
            get {
                return ResourceManager.GetString("TitleManageIndex", resourceCulture);
            }
        }
    }
}
